name: "Repo of the week"
description: "Edit your README.md to include 'Repo of the week' section."
author: matronator
branding:
  icon: "star"
  color: "yellow"

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    - run: bun install
      shell: bash
    - run: bun run refresh
      shell: bash
    - uses: stefanzweifel/git-auto-commit-action@v5
